import { type PageRecordConfig } from './types';

export const PAGES: PageRecordConfig[] = [
  {
    id: 'quickstart',
    name: 'Quickstart',
    filename: 'AgnoAngular - 01Quickstart',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/quickstart',
    ideFile: 'frontend/src/app/features/quickstart/quickstart-chat.ts',
    startLine: 1,
    endLine: 20,
    demoUrl: 'http://localhost:4200/quickstart/demo',
    prompt: 'Can you tell me a joke?',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'chat-ui',
    name: 'Chat UI & Customization',
    filename: 'AgnoAngular - 02ChatUi',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/chat-ui',
    ideFile: 'frontend/src/app/features/chat-ui/chat-ui-demo.component.ts',
    startLine: 28,
    endLine: 95,
    demoUrl: 'http://localhost:4200/chat-ui/demo',
    prompt: 'What is CopilotKit?',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'frontend-tools-generative-ui',
    name: 'Frontend Tools & Generative UI',
    filename: 'AgnoAngular - 03FrontendToolsGenUI',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/frontend-tools-generative-ui',
    ideFile: 'frontend/src/app/features/tools/tools-chat.component.ts',
    startLine: 20,
    endLine: 61,
    demoUrl: 'http://localhost:4200/frontend-tools-generative-ui/demo',
    prompt: "What's the weather in Tokyo?",
    waitAfterPromptMs: 4000,
  },
  {
    id: 'a2ui',
    name: 'A2UI Schemas, Styling & Recovery',
    filename: 'AgnoAngular - 04A2UI',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/a2ui',
    ideFile: 'frontend/src/app/features/a2ui/a2ui-chat.component.ts',
    startLine: 1,
    endLine: 23,
    demoUrl: 'http://localhost:4200/a2ui/demo',
    prompt: 'Show me a card comparing two flight options.',
    waitAfterPromptMs: 4000,
    docOnly: true,
  },
  {
    id: 'voice-multimodal',
    name: 'Voice & Multimodal Input',
    filename: 'AgnoAngular - 05VoiceMultimodal',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/voice-multimodal',
    ideFile: 'frontend/src/app/features/media/voice-chat.component.ts',
    startLine: 1,
    endLine: 28,
    demoUrl: 'http://localhost:4200/voice-multimodal/demo',
    prompt: 'Tell me what you can do with images and voice',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'human-in-the-loop',
    name: 'Human-In-The-Loop & Interrupts',
    filename: 'AgnoAngular - 06HumanInTheLoop',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/human-in-the-loop',
    ideFile: 'frontend/src/app/features/hitl/approval-card.component.ts',
    startLine: 1,
    endLine: 40,
    demoUrl: 'http://localhost:4200/human-in-the-loop/demo',
    prompt: 'Delete my account, but ask me to approve it first.',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'shared-state',
    name: 'Shared State & Agent Context',
    filename: 'AgnoAngular - 07SharedState',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/shared-state',
    ideFile: 'frontend/src/app/features/shared-state/workspace.component.ts',
    startLine: 1,
    endLine: 49,
    demoUrl: 'http://localhost:4200/shared-state/demo',
    prompt: 'What is my current priority and what notes do I have?',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'threads',
    name: 'Threads & Multi-Turn Conversations',
    filename: 'AgnoAngular - 08Threads',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/threads-memory-attachments-headless',
    ideFile: 'frontend/src/app/features/threads/threads-demo.component.ts',
    startLine: 1,
    endLine: 36,
    demoUrl: 'http://localhost:4200/threads/demo',
    prompt: 'Hello from thread management demo!',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'memory',
    name: 'Memory & State Persistence',
    filename: 'AgnoAngular - 09Memory',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/threads-memory-attachments-headless',
    ideFile: 'frontend/src/app/features/memory/memory-demo.component.ts',
    startLine: 1,
    endLine: 30,
    demoUrl: 'http://localhost:4200/memory/demo',
    prompt: 'Remember that I am working on an Angular 22 project',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'attachments',
    name: 'Attachments & File Uploads',
    filename: 'AgnoAngular - 10Attachments',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/threads-memory-attachments-headless',
    ideFile: 'frontend/src/app/features/attachments/media-chat.component.ts',
    startLine: 1,
    endLine: 24,
    demoUrl: 'http://localhost:4200/attachments/demo',
    prompt: 'What types of attachments are supported?',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'headless',
    name: 'Headless UI & Custom Composer',
    filename: 'AgnoAngular - 11HeadlessUI',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/guides/threads-memory-attachments-headless',
    ideFile: 'frontend/src/app/features/headless/headless-chat.component.ts',
    startLine: 1,
    endLine: 61,
    demoUrl: 'http://localhost:4200/headless/demo',
    prompt: 'Tell me a short joke about Angular',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'copilot-runtime',
    name: 'Copilot Runtime (Node.js + AgnoAgent)',
    filename: 'AgnoAngular - 12CopilotRuntime',
    docUrl: 'https://docs.copilotkit.ai/angular/agno/backend/copilot-runtime',
    ideFile: 'frontend/server.ts',
    startLine: 16,
    endLine: 45,
    demoUrl: 'http://localhost:4200/quickstart/demo',
    prompt: 'How does Copilot Runtime bridge Angular to Agno AgentOS?',
    waitAfterPromptMs: 4000,
  },
  {
    id: 'backend-agent',
    name: 'Backend — Agno AgentOS (Python / FastAPI)',
    filename: 'AgnoAngular - 13BackendAgent',
    docUrl: 'https://docs.copilotkit.ai/angular/agno',
    ideFile: 'backend/main.py',
    startLine: 35,
    endLine: 63,
    demoUrl: 'http://localhost:4200/quickstart/demo',
    prompt: 'What tools and models are configured in the Agno agent?',
    waitAfterPromptMs: 4000,
  },
];
